# Generated by Django 5.1.2 on 2025-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Nivel de importancia de la noticia', max_length=10),
        ),
    ]
