# Generated by Django 5.1.2 on 2025-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_news_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], help_text='Nivel de importancia de la noticia', max_length=10),
        ),
    ]
