# Generated by Django 5.1.2 on 2025-07-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_handle_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='first_processed_gamification_data',
            field=models.BooleanField(default=False, help_text='Indica si los datos de gamificación de este agente ya han sido procesados al menos una vez.'),
        ),
        migrations.AddField(
            model_name='user',
            name='gamification_level',
            field=models.IntegerField(default=1, help_text='Nivel actual de gamificación del agente.'),
        ),
        migrations.AddField(
            model_name='user',
            name='gamification_points',
            field=models.IntegerField(default=0, help_text='Puntos de gamificación acumulados por el agente.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_calls_handled',
            field=models.IntegerField(default=0, help_text='Último conteo de llamadas manejadas obtenido de Sharpen.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_point_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_quality_score',
            field=models.FloatField(default=0.0, help_text='Última puntuación de calidad obtenida de Sharpen.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_resolution_rate',
            field=models.FloatField(default=0.0, help_text='Última tasa de resolución obtenida de Sharpen.'),
        ),
        migrations.AddField(
            model_name='user',
            name='sharpen_username',
            field=models.CharField(blank=True, help_text='Username del agente en Sharpen, para asociar métricas.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_calls_handled',
            field=models.IntegerField(default=0),
        ),
    ]
