#TODO: definir variables de entorno
services:
  web:
    build: .
    container_name: gvhc_web
    command: daphne -b 0.0.0.0 -p 8000 gvhc.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - redis
    #   - db

  celery_worker:
    build: .
    container_name: gvhc_celery_worker
    command: celery -A gvhc worker --loglevel=info
    # volumes:
    #   - .:/app
    env_file:
      - .env
    # depends_on:
    #   - redis
    #   - db

  celery_beat:
    build: .
    container_name: gvhc_celery_beat
    command: celery -A gvhc beat --loglevel=info
    # volumes:
    #   - .:/app
    env_file:
      - .env
    # depends_on:
    #   - redis
    #   - db

  # redis:
  #   image: redis:7
  #   container_name: gvhc_redis
  #   ports:
  #     - "6379:6379"

  # db:
  #   image: postgres:15
  #   container_name: gvhc_postgres
  #   environment:
  #     POSTGRES_DB: gvhc_db
  #     POSTGRES_USER: gvhc_user
  #     POSTGRES_PASSWORD: gvhc_pass
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  pgdata:
