# Generated by Django 5.1.2 on 2025-07-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
