# Generated by Django 5.1.2 on 2025-07-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_monitor', '0002_callanalysis_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='language_used',
            field=models.CharField(blank=True, default='es', max_length=10, null=True),
        ),
    ]
