# Generated by Django 5.1.2 on 2025-07-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstation', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la variedad, ej: Salseado, Sin salsa, Picante', max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='foodstation.dish')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodstation.dishvariation'),
        ),
    ]
