app = "gvhc-beat"  
primary_region = "gru"  

[build]
  dockerfile = "../Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "gvhc.settings"
  MODE = "production"

[deploy]
  release_command = "python manage.py migrate --noinput"

[experimental]
  allowed_public_ports = []  

[processes]
beat = "celery -A gvhc beat --loglevel=info"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb" # Ajusta según la carga de tus tareas