# Generated by Django 5.1.3 on 2025-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteLlamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('total_llamadas', models.IntegerField()),
                ('llamadas_atendidas', models.IntegerField()),
                ('tmo', models.DurationField()),
                ('archivo_origen', models.FileField(upload_to='reportes/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
