# Generated by Django 5.1.3 on 2024-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_remove_answer_steps_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
