# Generated by Django 5.1.3 on 2024-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
