# Generated by Django 5.1.3 on 2024-11-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0006_answer_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='has_steps',
            field=models.BooleanField(default=False),
        ),
    ]
