# Generated by Django 5.1.3 on 2024-11-12 21:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0008_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
