# Generated by Django 5.1.3 on 2024-11-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0009_alter_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='node_type',
            field=models.CharField(choices=[('NonresizableNode', 'Nonresizable Node'), ('ResizableNodeSelected', 'Resizable Node'), ('Slide', 'Slide')], default='NonresizableNode', max_length=50),
        ),
    ]
