# Generated by Django 5.1.3 on 2024-11-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0010_answer_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='node_type',
            field=models.CharField(choices=[('NonresizableNode', 'Nonresizable Node'), ('ResizableNodeSelected', 'Resizable Node'), ('slidesToElements', 'slidesToElements')], default='NonresizableNode', max_length=50),
        ),
    ]
