# Generated by Django 5.1.2 on 2024-11-26 06:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0011_alter_answer_node_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerconnection',
            name='condition',
        ),
        migrations.AddField(
            model_name='answerconnection',
            name='decision_path',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('answer', 'number'), name='unique_step_per_answer'),
        ),
    ]
