# Generated by Django 5.1.2 on 2024-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0013_alter_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='node_type',
            field=models.CharField(choices=[('NonresizableNode', 'Nonresizable Node'), ('ResizableNodeSelected', 'Resizable Node'), ('slidesToElements', 'slidesToElements'), ('TooltipNode', 'Tooltip Node'), ('AnnotationNode', 'Annotation Node'), ('NoteNode', 'Note Node')], default='NonresizableNode', max_length=50),
        ),
    ]
