# Generated by Django 5.1.3 on 2024-12-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0015_alter_answer_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='node_type',
            field=models.CharField(choices=[('CustomResizableNode', 'CustomResizableNode'), ('NonResizableNode', 'NonResizableNode'), ('slidesToElements', 'slidesToElements'), ('TooltipNode', 'Tooltip Node'), ('AnnotationNode', 'Annotation Node'), ('NotesNode', 'Note Node')], default='NonresizableNode', max_length=50),
        ),
    ]
