# Generated by Django 5.1.3 on 2025-01-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0018_alter_answer_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='steps/excel_files/'),
        ),
    ]
