# Generated by Django 5.1.3 on 2025-02-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0019_step_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='queue_type',
            field=models.CharField(choices=[('MR', 'Medical Records'), ('Scheduling', 'Scheduling'), ('Referrals', 'Referrals'), ('Artera', 'Artera')], default='Scheduling', max_length=10),
        ),
    ]
