# Generated by Django 5.1.3 on 2025-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0021_alter_faq_queue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='queue_type',
            field=models.CharField(choices=[('MR', 'Medical Records'), ('Scheduling', 'Scheduling'), ('Referrals', 'Referrals'), ('Artera', 'Artera')], default='Scheduling', max_length=20),
        ),
    ]
