# Generated by Django 5.1.3 on 2025-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0022_alter_faq_queue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
