# Generated by Django 5.1.3 on 2025-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0023_faq_pos_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
