# Generated by Django 5.1.3 on 2025-06-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0025_alter_answer_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='node_type',
            field=models.CharField(choices=[('CustomResizableNode', 'Custom Resizable Node'), ('NonResizableNode', 'Non Resizable Node'), ('slidesToElements', 'slides To Elements'), ('TooltipNode', 'Tool tip Node'), ('AnnotationNode', 'Annotation Node'), ('NotesNode', 'Note Node'), ('TemplateNode', 'Template Node')], default='NonresizableNode', max_length=50),
        ),
    ]
