# Generated by Django 5.1.3 on 2025-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0026_alter_answer_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
