# Generated by Django 5.1.3 on 2025-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0027_answer_pos_x_answer_pos_y_step_pos_x_step_pos_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='node_type',
            field=models.CharField(choices=[('CustomResizableNode', 'Custom Resizable Node'), ('NonResizableNode', 'Non Resizable Node'), ('slidesToElements', 'slides To Elements'), ('TooltipNode', 'Tool tip Node'), ('AnnotationNode', 'Annotation Node'), ('NotesNode', 'Note Node'), ('TemplateNode', 'Template Node')], default='NonResizableNode', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='queue_type',
            field=models.CharField(choices=[('MR', 'Medical Records'), ('Scheduling', 'Scheduling'), ('Referrals', 'Referrals'), ('Artera', 'Artera'), ('Dental', 'Dental'), ('PACE', 'PACE')], default='Scheduling', max_length=20),
        ),
    ]
