# Generated by Django 5.1.3 on 2025-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0029_rename_category_department_remove_faq_queue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Protocols', 'Protocols'), ('Tips', 'Tips'), ('Payrolls', 'Payrolls'), ('Escalations', 'Escalations'), ('FeedBack', 'FeedBack')], default='Protocols', max_length=20),
        ),
    ]
