# Generated by Django 5.1.2 on 2025-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0030_alter_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='step',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
